sudo: required
dist: trusty

before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - sudo pip install apache-beam[gcp]
  - sudo pip install google-api-python-client pyyaml s2sphere pytest fiona shapely unidecode 
  - sudo pip https://api.github.com/repos/GlobalFishingWatch/pipe-tools/tarball/14-logging-options


script:
  - ./test_all
