sudo: required
dist: trusty

before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - sudo pip install apache-beam[gcp]
  - sudo pip install google-api-python-client pyyaml s2sphere pytest

script:
  - ./test_all