language: python

sudo: required

services: docker

cache:
  directories:
  - ~/.cache/pip

python:
- 3.7

install:
  - docker volume create --name=gcp
  - echo "$DOCKER_USRENAME"
  - docker-compose build

script:
  - docker-compose run test
