steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build-scheduler
  args: [
    'build',
    '-t', '${_SCHEDULER_IMAGE_NAME}:${TAG_NAME}',
    '-t', '${_SCHEDULER_IMAGE_NAME}:latest',
    '-f', 'Dockerfile-scheduler',
    '.',
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: test
  waitFor: ['build-scheduler']
  args: [
    'run',
    '--rm',
    '--entrypoint', 'py.test',
    '${_SCHEDULER_IMAGE_NAME}:latest',
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: build-worker
  waitFor: ['test']
  args: [
    'build',
    '-t', '${_WORKER_IMAGE_NAME}:${TAG_NAME}',
    '-t', '${_WORKER_IMAGE_NAME}:latest',
    '-f', 'Dockerfile-worker',
    '.',
  ]

images:
  - '${_SCHEDULER_IMAGE_NAME}:${TAG_NAME}'
  - '${_SCHEDULER_IMAGE_NAME}:latest'
  - '${_WORKER_IMAGE_NAME}:${TAG_NAME}'
  - '${_WORKER_IMAGE_NAME}:latest'

timeout: 600s
substitutions:
  _BASE_IMAGE_NAME: 'gcr.io/${PROJECT_ID}/github.com/globalfishingwatch/pipe-anchorages'
  _SCHEDULER_IMAGE_NAME: '${_BASE_IMAGE_NAME}/scheduler'
  _WORKER_IMAGE_NAME: '${_BASE_IMAGE_NAME}/worker'
options:
  dynamic_substitutions: true

