steps:

- name: 'gcr.io/cloud-builders/docker'
  id: build
  args: [
    'build',
    '-t',
    'gcr.io/$PROJECT_ID/github-globalfishingwatch-anchorages_pipeline:latest',
    '-t',
    'gcr.io/$PROJECT_ID/github-globalfishingwatch-anchorages_pipeline:$TAG_NAME',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: test
  args: [
    'run',
    '--rm',
    '--entrypoint',
    '/usr/local/bin/py.test',
    'gcr.io/$PROJECT_ID/github-globalfishingwatch-anchorages_pipeline:latest'
  ]
  waitFor: [ 'build' ]

- name: 'gcr.io/cloud-builders/docker'
  id: push_latest
  args: [
    'push',
    'gcr.io/$PROJECT_ID/github-globalfishingwatch-anchorages_pipeline:latest'
  ]
  waitFor: [ 'build', 'test' ]

- name: 'gcr.io/cloud-builders/docker'
  id: push_tagged
  args: [
    'push',
    'gcr.io/$PROJECT_ID/github-globalfishingwatch-anchorages_pipeline:$TAG_NAME'
  ]
  waitFor: [ 'build', 'test' ]

timeout: 7200s
