FROM gcr.io/world-fishing-827/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.7

# Setup scheduler-specific dependencies
COPY ./requirements-scheduler.txt ./
RUN pip install -r requirements-scheduler.txt

# Setup worker-specific dependencies
COPY ./requirements-worker.txt ./
RUN apt-get update && \
    apt-get -qy install gdal-bin libgdal-dev && \
    export GDAL_VERSION="$(gdal-config --version)" && \
    pip install -r requirements-worker.txt

# Setup local package
COPY . /opt/project
RUN pip install -e .

# Setup the entrypoint for quickly executing the pipelines
ENTRYPOINT ["./main.py"]
