FROM apache/beam_python3.7_sdk:2.40.0

# Setup local application dependencies
COPY ./requirements-worker.txt ./
RUN apt-get update && \
    apt-get -qy install gdal-bin libgdal-dev && \
    export GDAL_VERSION="$(gdal-config --version)" && \
    pip install -r requirements-worker.txt
